config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :users
      resources :lists
      resources :items
      resources :sessions, only: [:create, :destroy] do
        collection do
          get :current, to: 'sessions#current'
        end
      end

      resources :urls, only: :index

      match '/*path', to: 'api#handle_options_request', via: [:options]
    end
  end

  # resources :users
  resources :lists

  devise_for :users do
    resources :users
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  include IdentityCache

  belongs_to :list, touch: true
end

app/models/list.rb
class List < ActiveRecord::Base
  include IdentityCache

  belongs_to :user

  has_many :items, dependent: :destroy

  cache_has_many :items, embed: true
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  respond_to :json

  skip_before_action :verify_authenticity_token

  before_filter :set_general_access_control_headers
  before_action :authenticate_api_key

  skip_before_action :authenticate_api_key, only: :handle_options_request

  def render_message(head, status_code, message)
    render json: { head => { message: message } }, status: status_code
  end

  def handle_options_request
    headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-api-key, Content-Type'
    headers['Access-Control-Max-Age']       = '300'
    head :ok
  end

  private

  def set_general_access_control_headers
    # The P3P header is needed for IE to properly return
    # cookies in JSONP requests.
    headers['P3P'] = "CP='NOI ADM DEV COM NAV OUR STP'"

    headers['Access-Control-Allow-Origin'] = '*'
    # headers['Access-Control-Allow-Credentials'] = 'true'
  end

  def authenticate_api_key
    api_key = params[:api_key] || request.headers['X-api-key']
    render_message(:auth, 401, 'Invalid API key') if api_key.nil? or api_key != '1234'
  end

end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < Api::V1::ResourceController

  private

  def resource
    Item
  end

  def permit_params
    [:title, :price, :notes, :image, :link, :quantity, :priority, :reserved, :list_id]
  end

end

app/controllers/api/v1/lists_controller.rb
class Api::V1::ListsController < Api::V1::ResourceController

  private

  def resource
    List
  end

  def permit_params
    [:title, :start_date, :end_date, :user_id]
  end

end

app/controllers/api/v1/resource_controller.rb
class Api::V1::ResourceController < Api::V1::ApiController
  respond_to :json

  before_action :set_object, only: [:show, :update, :destroy]

  attr_accessor :object

  def index
    if params[:ids].present? and params[:ids].is_a? Array
      objects = resource.where(id: params[:ids])
    else
      objects = resource.paginate(page: params[:page], per_page: params[:per_page])
    end

    respond_with objects
  end

  def show
    respond_with object
  end

  def create
    respond_with :api, :v1, resource.create(object_params)
  end

  def update
    respond_with object.update(object_params)
  end

  def destroy
    respond_with object.destroy
  end

  private

  def resource
    raise "All subclasses must write this method!!"
  end

  def set_object
    @object = resource.where(id: params[:id]).first
    render_object_not_found if @object.nil?
  end

  def object_params
    params.require(object_sym).permit(permit_params)
  end

  def object_sym
    resource.to_s.downcase.to_sym
  end

  def permit_params
    raise "All subclasses must write this method!!"
  end

  def render_object_not_found
    render_message(object_sym, 404, "#{resource.to_s} ID not recognized.")
  end

end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::ApiController
  respond_to :json

  before_action :set_user, only: [:create]

  attr_accessor :user

  def create
    sign_in user
    render json: { id: user.id, email: user.email }
  end

  def destroy
    sign_out :user
    render nothing: true, status: :accepted
  end

  def current
    if current_user.present?
      render json: { user: { id: current_user.id, email: current_user.email } }
      # respond_with current_user
    else
      render_message(:session, 200, "No current user session.")
    end
  end

  private

  def set_user
    @user = User.find_for_database_authentication(email: params[:session][:email])

    unless user && user.valid_password?(params[:session][:password])
      render_message(:session, 422, "Invalid Email or Password")
    end
  end

end

app/controllers/api/v1/urls_controller.rb
class Api::V1::UrlsController < Api::V1::ApiController

  def index
    raise_not_found if params[:url].nil?

    @url = ProductParser.new(params[:url])
    @url.parse!
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ResourceController

  private

  def resource
    User
  end

  def permit_params
    [:email, :first_name, :last_name, :password, :password_confirmation]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def raise_not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
# Taken from:
# https://github.com/plataformatec/devise/wiki/How-To:-Integrate-I18n-Flash-Messages-with-Devise-and-Bootstrap
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1>Create a Universal Wishlist</h1>
    </div>

    <div class="col-md-9">
      <p>Explore new lists</p>
      <ul>
        <% List.all.each do |l| %>
          <li><%= link_to l.title, list_path(l) %></li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Just Another Wishlist Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Wishly', root_path, { :class => 'navbar-brand'} %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% unless current_user.present? %>
        <li><%= link_to 'Register', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% else %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% end %>
<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
 -->      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

</body>
</html>